server:
 port: 8012
spring:
 application:
   name: sitterbootcamp
 datasource:
   driverClassName: org.postgresql.Driver
   initialization-mode: NEVER
   password: ${DB_PASSWORD:Williams93}
   url: jdbc:postgresql://${DB_URL:localhost}:5432/${DB_NAME:grocery_list}
   username: ${DB_USERNAME:postgres}
 jpa:
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   generate-ddl: false
   hibernate:
     ddl-auto: none
   properties:
     hibernate:
       default_schema: ${DB_SCHEMA:public}
   show-sql: false